# This is for gke app deployment
# This is a basic workflow to help you get started with Actions

name: GKE app deployment using Github

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_ID: kube-project-385314
  GKE_CLUSTER: apc-pn
  GKE_REGION: us-east1


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup Gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.3
        env: 
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with: 
          service_account_key: ${{ secrets.GCP_TOKEN }}
          project_id: kube-project-385314

      - name: GKE credentials
        run: |-
          gcloud container clusters get-credentials apc-pn --region us-east1 --project kube-project-385314
   
      - name: Apply the yaml file
        run: |
          ./run.sh
